### PR TITLE
Replace `find_module` and `load_module` for Python 3.12 compatibilty

### LINKED ISSUE #57: Python 3.12 compatibility
It looks like the `find_module` method got removed in Python 3.12:

```
 _warnings.warn("find_module() is deprecated and "
                   "slated for removal in Python 3.12; use find_spec() instead",
                   DeprecationWarning)
```

resulting in

```
    from .parsers import Parser
  File "/path/to/hepdata_converter/parsers/__init__.py", line 178, in <module>
    module = loader.find_module(name).load_module(name)
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```

when trying to import the `hepdata_converter`

### PR DESCRIPTION
**Pull request by GraemeWatt**
* `find_module` deprecated since Python 3.10 and removed in Python 3.12.
* `load_module` deprecated since Python 3.4.
* Closes #57.

### CODE REVIEW

**Review by 20DM — APPROVED** [review]
Thanks for the patch - I pulled this on my Mac and can confirm that this works fine with Python 3.12! 🙏
